#!/usr/bin/env python3
"""gen_launchers.py — emit Linux launchers from a SOC Master Widget registry.

For every registry app with a `cmd_linux`, writes into <out>/launchers/:
  <slug>.sh        — cd to the app dir and exec the command
  <slug>.desktop   — freedesktop entry (Exec points at the .sh)
plus start_stack.sh — launches the in_stack apps in `order` with the same
~1.8 s spacing the widget uses.

Usage:  python gen_launchers.py [--config soc_master_apps.json] [--out .]
Stdlib only. Windows-only apps (no cmd_linux) are skipped, listed at the end.
"""
from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from pathlib import Path

STACK_DELAY_SECS = 1.8  # matches the widget's Start Stack spacing


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "app"


def sh_quote(parts: list[str]) -> str:
    return " ".join(shlex.quote(p) for p in parts)


def linux_dir(app: dict) -> str:
    return app.get("dir_linux") or app.get("dir", ".")


def gen(config_path: Path, out_root: Path) -> tuple[list[str], list[str]]:
    """Returns (written_files, skipped_app_names)."""
    data = json.loads(config_path.read_text(encoding="utf-8"))
    apps = sorted(data.get("apps", []), key=lambda a: a.get("order", 99))
    launch_dir = out_root / "launchers"
    launch_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    skipped: list[str] = []
    stack_lines = ["#!/usr/bin/env bash", "# Start Stack — generated by gen_launchers.py", "set -u", ""]

    for a in apps:
        cmd = a.get("cmd_linux")
        if not cmd:
            skipped.append(a.get("name", "?"))
            continue
        name = a.get("name", "app")
        slug = slugify(name)
        d = linux_dir(a)
        sh_path = launch_dir / f"{slug}.sh"
        sh_path.write_text(
            "#!/usr/bin/env bash\n"
            f"# {name} — generated by gen_launchers.py; edit the registry, not this file\n"
            "set -u\n"
            f"cd {shlex.quote(d)}\n"
            f"exec {sh_quote(cmd)}\n",
            encoding="utf-8", newline="\n")
        written.append(str(sh_path))
        desktop_path = launch_dir / f"{slug}.desktop"
        desktop_path.write_text(
            "[Desktop Entry]\n"
            "Type=Application\n"
            f"Name={name}\n"
            f"Comment={a.get('note', '')}\n"
            f"Exec=bash {shlex.quote(str(sh_path))}\n"
            f"Path={d}\n"
            f"Terminal={'true' if a.get('console', True) else 'false'}\n"
            "Categories=Utility;\n",
            encoding="utf-8", newline="\n")
        written.append(str(desktop_path))
        if a.get("in_stack", True):
            stack_lines += [f"# [{a.get('order','?')}] {name}",
                            f"bash {shlex.quote(str(sh_path))} &",
                            f"sleep {STACK_DELAY_SECS}", ""]

    stack = launch_dir / "start_stack.sh"
    stack.write_text("\n".join(stack_lines) + 'echo "stack launched"\n', encoding="utf-8", newline="\n")
    written.append(str(stack))
    return written, skipped


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(Path(__file__).with_name("soc_master_apps.json")))
    ap.add_argument("--out", default=str(Path(__file__).parent))
    args = ap.parse_args(argv)
    written, skipped = gen(Path(args.config), Path(args.out))
    for w in written:
        print(f"wrote  {w}")
    for s in skipped:
        print(f"skip   {s} (no cmd_linux yet)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
